apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  name: schema-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: ef-migration
        image: mcr.microsoft.com/dotnet/sdk:6.0
        command: ["/bin/bash","-c",  "apt install git -y && git clone $GIT_REPO && cd $SERVICE_PATH && dotnet tool install --global dotnet-ef && export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet ef database update"]
        env:
        - name: GIT_REPO
          value: https://github.com/ragoob/gitops-dotnet-web-app.git
        - name: ConnectionStrings__DefaultConnection
          value: Host=postgres.postgres.svc.cluster.local;Port=5432;Database=product_db;Username=postgres;Password=postgres
        - name: SERVICE_PATH
          value: gitops-dotnet-web-app/productService
      restartPolicy: Never
