kind: Service
apiVersion: v1
metadata:
  name:  product-service
  annotations:
        linkerd.io/inject: enabled
spec:
  selector:
    app:  product-service
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  80