apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: regoo707/product-service
  newTag: 2019eff
configMapGenerator:
  - name: product-service-cm
    envs:
      - .env