apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
images:
- name: regoo707/product-service
  newTag: b23b06c
configMapGenerator:
  - name: product-service
    envs:
      - .env